name: build
on:
  push:
    branches:
      - main

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/nginx
  NGINX_VERSION: 1.23.3

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            "NGINX_VERSION=${{ env.NGINX_VERSION }}"
          tags: ${{ env.IMAGE }}:latest

  readme:
    needs: [ build-image ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README.md
        run: |
          README=$(<README.template.md)
          README="${README//%%IMAGE%%/$IMAGE}"

          README="${README//%%NGINX_VERSION%%/$NGINX_VERSION}"

          echo "$README" > README.md

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.1.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE }}

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Automated Change
          file_pattern: '*.md'
